### ISSUE TITLE
Have a tool to ensure the distance between the two connectors

### ISSUE THREAD

**Issue by Rufus31415** [Rufus31415/arduino-pro-portenta-h7-carrier-board#7]
The gap between the 2 connectors is very important and should be constrained

**Comment by pnndra** [comment]
we can provide you with an altium project template with preplaced connectors

**Comment by swittman** [comment]
@pnndra I'm also interested in this, but rather for CircuitMaker. In the short term, can you verify what the spacing between the two connectors should be? Is there any plan to provide pre-composed footprints/CAD though a library like Octopart?
